---
title: "Geography 176A"
author: "Chelsey Su"
subtitle: "Daily Exercise 18"
output:
    html_document:
      theme: journal
---
```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(sf)
library(elevatr)
library(raster)
library(readr)
library(rgdal)
```

```{r}
goleta = read_csv("~/github/geog176A-daily-exercises/data/uscities.csv") %>%  
  st_as_sf(coords = c("lng", "lat"), crs = 4326) %>%
  st_transform(5070) %>%
  filter(city == "Goleta") %>%
  st_buffer(5000) %>% 
  st_bbox(z = 20) %>% 
  st_as_sfc() %>% 
  st_as_sf()

elev = elevatr::get_elev_raster(goleta, z = 10) %>% 
  crop(goleta)

writeRaster(elev, filename = "~/github/geog176A-daily-exercises/data/goleta-elev.tif", overwrite = TRUE)

elevation = raster("~/github/geog176A-daily-exercises/data/goleta-elev.tif")

threshold = function(x){ifelse(x <= 0, NA, 1)}

m = calc(elevation, threshold)

ocean_cut = elevation * m

rcl = data.frame(min = seq(0, 500, 100), max = seq(100, 600, 100), lab = c(0:5))

rc = reclassify(ocean_cut, rcl, lowerTRUE = TRUE)

s = stack(elevation, m, ocean_cut, rc) %>% 
  setNames(c("Elevation", "Land-mask", "Terrain", "Topography"))

  plot(s, col = viridis::viridis(256))
```

